services:
  - type: web
    name: delta-assistant
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: GEMINI_API_KEY_1
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
    healthCheckPath: /status
